FROM python:3.11-slim

WORKDIR /app

COPY requirements.mock.txt .
RUN pip install --no-cache-dir -r requirements.mock.txt

COPY scripts/mock_producer.py ./mock_producer.py

CMD ["python", "mock_producer.py"]
