version: '2.1'
services:
  edge-camera-1:
    build: .
    environment:
      - CAMERA_ID=cam_01
      - CAMERA_URL=tests/test_video.mp4
      - MODEL_PATH=yolov8n.pt
      - TRACKER_CONFIG=bytetrack.yaml
      - FRAME_SKIP=1
      - STATUS_INTERVAL_SECONDS=5
      - LOG_DETECTIONS=false
      - KAFKA_BOOTSTRAP_SERVERS=139.59.85.137:32092
      - KAFKA_TOPIC=traffic.events.raw
      - API_PORT=8001
      - KAFKA_ENABLED=true
      - KAFKA_SECURITY_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_SASL_MECHANISM=PLAIN
      - KAFKA_USERNAME=its-b1-producer
      - KAFKA_PASSWORD=ITS@B1prod2026
